### ISSUE TITLE
Test model

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8lok#2]
Please test that this model works on Google Colab and on Ersilia's CLI

Thanks!

**Comment by Zainab-ik** [comment]
On it.

**Comment by Zainab-ik** [comment]
## **Testing Enviroment  - Ersilia CLI**

### Step 1: Fetch model `eos8lok.`
Code: ` ersilia -v fetch eos8lok > eos8lokLogfile.log 2>&1`
The model fetched successfully.
Attached log file 
[eos8lok_Logfile.log](https://github.com/ersilia-os/eos8lok/files/11082790/eos8lok_Logfile.log)

### Step 2: Serve Model
code: `ersilia serve eos8lok`
The model served successfully with `Api: run`.
This is a new API compared with ersilia's APIs which are `predict` and `calculate.`
![image](https://user-images.githubusercontent.com/54579707/228060204-d264448b-9bab-490d-b2cb-04cb338f56c3.png)

### Step 3: Run predictions with model
code: `ersilia -v api run -i "CCCC" > eos8lokRun.log 2>&1`
The API `run` is first tested with a single compound `CCCC`.
The model ran successfully
output log is attached. 
[eos8lokRun.log](https://github.com/ersilia-os/eos8lok/files/11082894/eos8lokRun.log)

I'd like to test it with the `eml_canonical.csv` file.
code: `ersilia -v api run -i eml_canonical.csv -o eos8lokOutput.csv > output.log 2>&1`
The `eml_canonical.csv` was run successfully.
Output CSV file attached: [eos8lokOutput.csv](https://github.com/ersilia-os/eos8lok/files/11083064/eos8lokOutput.csv)
Output log file: [output.log](https://github.com/ersilia-os/eos8lok/files/11083066/output.log)

> The model `eos8lok` was tested and worked successfully on Ersilia CLI

**Comment by Zainab-ik** [comment]
@GemmaTuron, I'd like to ask how the APIs of the models are generated.

**Comment by Zainab-ik** [comment]
## **Testing Environment   - Google Colab**
 Link to code - [Colab](https://colab.research.google.com/drive/1J_0qJsTYTwzervrcs__68-kVftDFRyMi?usp=sharing)

The model was successfully fetched, served, and a prediction was made. 
Attached is the output file  - [eos8lok_output.csv](https://github.com/ersilia-os/eos8lok/files/11087372/eos8lok_output.csv)


> Model worked successfully on Google Colab

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik !

Wonderful, thanks for testing that! Now let's focus on writing your final application

**Comment by GemmaTuron** [comment]
@AhmedYusuff

Can you also test this model? We always test them twice to make sure they are working in different systems.
Thanks!

**Comment by GemmaTuron** [comment]
@Zainab-ik 
The model APIs are defined by us, we used to have different ones but now we have decided to call all of them "run" to make it easier

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik !
> 
> Wonderful, thanks for testing that! Now let's focus on writing your final application

Thank you @GemmaTuron

**Comment by Zainab-ik** [comment]
> @Zainab-ik The model APIs are defined by us, we used to have different ones but now we have decided to call all of them "run" to make it easier

That's interesting.
So there's no API as `predict` or `calculate` any longer.
I think it's a great improvement. The results would then determine whether is a calculation or a description, right?
@GemmaTuron

**Comment by AhmedYusuff** [comment]
Hi @GemmaTuron.

### EOS8LOK MODEL TEST

I Tested the Model on my Ubuntu 22.04 system and Google Colab.

### Result
---
- [x] Model was fetched, served, and Predicted successfully on Google  Colab.
- Link to Colab Notebook. [Colab](https://colab.research.google.com/drive/1J_0qJsTYTwzervrcs__68-kVftDFRyMi?usp=sharing)
- Colab output file.  [eos8lok_output.csv](https://github.com/ersilia-os/eos8lok/files/11092336/eos8lok_output.csv)
 
- [x] Model was fetched, served, and Predicted successfully on Ubuntu 22.04.

- Fetch Log. [eosfetch.log](https://github.com/ersilia-os/eos8lok/files/11092373/eosfetch.log)

- Output File.  [eos8lokoutput.csv](https://github.com/ersilia-os/eos8lok/files/11092376/eos8lokoutput.csv)
